-- IVE 일정 테이블 (Supabase SQL Editor에서 실행)
create table if not exists public.schedules (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null check (category in ('concert', 'comeback', 'broadcast', 'fanmeeting', 'popup', 'release', 'etc')),
  starts_at timestamptz not null,
  ends_at timestamptz,
  location text,
  link text,
  source text not null default 'manual',
  created_at timestamptz not null default now()
);

-- 누구나 읽기 가능, 쓰기는 대시보드(서비스롤)에서만
alter table public.schedules enable row level security;

create policy "schedules_public_read" on public.schedules
  for select using (true);

-- 샘플 데이터 (확인 후 삭제하고 실제 일정 입력)
insert into public.schedules (title, category, starts_at, ends_at, location, link) values
  ('미니브 팝업 스토어 부산', 'popup', '2026-08-14 10:00+09', '2026-08-23 20:00+09', '부산 신세계 센텀시티', null),
  ('NOL FESTIVAL', 'concert', '2026-09-12 17:00+09', null, '서울 올림픽공원', null);
